import React, { useState, useEffect } from 'react';
import { ethers } from 'ethers';

export default function GaslessDonation() {
    const [userAddress, setUserAddress] = useState("");
    const [usdAmount, setUsdAmount] = useState("10"); 
    const [loading, setLoading] = useState(false);
    const [logs, setLogs] = useState("System Ready... Connect to proceed.");

    const addLog = (msg) => setLogs(prev => prev + `\n> ${msg}`);

    // Connect user wallet (MetaMask) on component load
    const connectWallet = async () => {
        if (!window.ethereum) {
            addLog("❌ MetaMask not found. Please install the browser extension.");
            return;
        }
        try {
            const provider = new ethers.BrowserProvider(window.ethereum);
            const accounts = await provider.send("eth_requestAccounts", []);
            setUserAddress(accounts[0]);
            addLog(`Connected to user wallet: ${accounts[0]}`);
        } catch (error) {
            addLog(`❌ Wallet link rejected: ${error.message}`);
        }
    };

    useEffect(() => {
        connectWallet();
    }, []);

    const handleUgfRemoteDonation = async () => {
        if (!userAddress) {
            addLog("❌ Please connect your wallet first.");
            return;
        }

        setLoading(true);
        addLog(`🚀 1. Triggering integrated secure gasless payment route for $${usdAmount}...`);

        try {
            // 🌟 INTEGRATION FIX: Retrieve the token generated by your teammate's /verify endpoint
            const savedAuthToken = localStorage.getItem("jwt_token"); 

            if (!savedAuthToken) {
                throw new Error("No active authorization token found. Please sign in via the login panel first.");
            }

            addLog("Transmitting parameters with Authorization token to backend UGF handler...");

            // ✅ Pass token through headers and drop user_address from the payload
            const response = await fetch("/api/transactions/ugf-remote-send", {
                method: "POST",
                headers: { 
                    "Content-Type": "application/json",
                    "Authorization": `Bearer ${savedAuthToken}` // 🔒 Protects the route
                },
                body: JSON.stringify({ 
                    amount_usd: usdAmount
                })
            });

            if (response.status === 401) {
                throw new Error("Unauthorized access. Token might be invalid or expired.");
            }

            const resultData = await response.json();

            if (resultData.status !== 'success') {
                throw new Error(resultData.message);
            }

            // Success Confirmation Status Updates
            addLog("🎉 UGF Remote Execution Completed Successfully!");
            addLog(`⛽ Gas fully settled via server operator asset index!`);
            addLog(`⛓️ Asset Used: ${resultData.data.asset}`);
            addLog(`🔗 Live Network Transaction Hash: ${resultData.data.route_hash}`);

        } catch (error) {
            console.error(error);
            addLog(`❌ UGF Route Halting Error: ${error.message}`);
        } finally {
            setLoading(false);
        }
    };

    return (
        <div style={{ fontFamily: 'monospace', padding: '20px', maxWidth: '600px', margin: 'auto', background: '#fff', borderRadius: '8px', border: '1px solid #ddd', marginTop: '40px' }}>
            <h2>🌱 FasalIQ Gasless GreenDonations Panel</h2>
            <p><strong>Your External Wallet Address:</strong><br />
               <span style={{ color: '#007bff', fontSize: '13px' }}>{userAddress || "Connecting MetaMask Account..."}</span>
            </p>
            
            <hr />

            <div style={{ marginBottom: '15px' }}>
                <label style={{ display: 'block', fontWeight: 'bold' }}>Donation Value (USD Amount):</label>
                <input 
                    type="number" 
                    value={usdAmount} 
                    onChange={(e) => setUsdAmount(e.target.value)}
                    style={{ padding: '10px', width: '95%', fontSize: '16px', display: 'block', marginTop: '5px', boxSizing: 'border-box' }}
                />
            </div>

            <button 
                onClick={handleUgfRemoteDonation} 
                disabled={loading || !userAddress}
                style={{
                    padding: '12px 24px',
                    background: '#28a745',
                    color: 'white',
                    border: 'none',
                    borderRadius: '4px',
                    cursor: userAddress ? 'pointer' : 'not-allowed',
                    fontWeight: 'bold',
                    width: '100%',
                    fontSize: '15px'
                }}
            >
                {loading ? "Processing Secure Payment..." : "🔗 Send Donation (Pay Gas with TYI USD)"}
            </button>

            <h3>Console Feedback Logs:</h3>
            <pre style={{ background: '#111', color: '#0f0', padding: '15px', borderRadius: '5px', maxHeight: '250px', overflowY: 'auto', whiteSpace: 'pre-wrap', textAlign: 'left' }}>
                {logs}
            </pre>
        </div>
    );
}